language: node_js

node_js:
- node

cache:
  directories:
  - node_modules

before_script:
- npm install -g serverless

env:
  global:
  - secure: uaLtfjSbjlUUQp7SQvOIW9X6TxDqI51yQ41z5V3OSoZdNCeaY9p+k8iX8Qcdod1aNT6qNXH3a6cIgzR+8QPct43PO9glYXZSnZ/zmjEDlAw4d9qwShfu3vlXafACsJ56EyLvt/1Ee7A7VhV7ttFZf+NxD2bJYykRTQV3xRWKDzMVwW+XN7s2sKkS3mGrhr0bqvQ7IdJWO15WI3HynVBsoG9ZYy5qoVT8MDAVv6iJcJFJDfCiGItL2fu0PvdHlQShMMdoxU1LSHfdP87M2EnoUD3HCV+Ws8hmMC5a4+1r6BxXe7Y3Z20izzc5IEA7OWEQtG+6q9Ig7p46PXENwUZviieyE1gB7gDCR3gmDz6/JH2qsNzyftKufX+YHq/ZZuALkdGopYvXhZGnqyz5wxDVJKFTsYxM1sr1Baxjhu6U9ugLYh85NSyRR2jkQ7tlOVBykl85fh1PMN1m1RLReneFJ+L8UmaRG7sbIM+lT/kvPGjbEwkvvfx1V8pC7a6tlw1N15QPiGC8kN9mk2iqmEryfTncNc9+3KCiJ/bOsxKbkJn/pkx6DUn7T8Ysf0SJNdW5WXCnVMtuFRAyr+XVwphAjJw2jopCLc9hW/2AVxeyd/ZlYIQ/GeGxdUkjEo3qJe9OiY+bjptmoqlyXG6a1fxMKtd0D/kKo7zaGtC86sxQh+A=
  - secure: NSAzgYIYgsQFH0NQabacUP+LDkx9/ea+s/vgnw4vPcTMfHd2SP5I3DPDPA4pS31z5FtFHjsjieqdK1eZ9GUloAteP2dHGay4B3HRLiAodshKLpSPXBPFfS7s+c8rOLWvEHY6+unNkd90pIjiEBQIsVJV9FEtX0FTMZ39g/Oos4RfwFsKcd6sVBtBXY/xnn0b5VEW7Xp88hTpOyaiAm6tMMXN7Y4Dy6l2p+/ibjMB0BBqRyOBKnv6MrznABFRpzCL9giLhgU9etPVVAeQnW26JvOsSelJTIwvufi9paUuvt3m7BX5HIHWtX3qI19gsXEAo2UwmYu2ajc5mzbWvzDsJcY2vle3glJqxRIpoWsJXGXQKgNQP9DcmmSFuEjks0VCDeaiE5qoxtp175KgcDRPl8MmzOAIqscNWB8rmxYqU/TCu+bOKs0uypdKu0ZqvOEszU0E9grDG1wZ7MCi2zKWSqGow+LcpZuDjfJ2a5ax6kJOeLtlezrI8O8ccOVmZg+y+6lOXhUR1lHkekHBHmRCxHrRieuFd42nrh7MbsqnWxHMuBw1ZQfiZyfg8vmNyru4VDvQtwfcpq2pow2ifM4YrIdbxCW/XUiBpec3JyA2Hhx6aQ1nQAmK4BGy55DNybMCEJIuXNmGRkCsajR7XS3jtop5weSj3gXAbrHxWe2kJdg=

deploy:
  provider: script
  script: serverless deploy
  on:
    branch: master
